### ISSUE TITLE
bug: function crashes when spotify is playing ads

### ISSUE THREAD

**Issue by egoist** [akellbl4/spotify-badge#7]
error message:

```
Cannot destructure property 'duration_ms' of 'item' as it is null.",
"stack":["TypeError: Cannot destructure property 'duration_ms' of 'item' as it is null.","    
at formatTrackInfo (/vercel/path2/lib/spotify.ts:51:23)","    
at Object.getNowPlaying (/vercel/path2/lib/spotify.ts:73:9)
```

**Comment by akellbl4** [comment]
Thanks for report. I'll take a look today.

**Comment by akellbl4** [comment]
@egoist could you please check if fix works?

**Comment by akellbl4** [comment]
I'm gonna close this issue. If the bug appears feel free to reopen it
